# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Redirects"
client_id = "f8d0d9b4a674d6846daa8a45c6bb3a71"
application_url = "https://currently-editorial-protective-philosophy.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://currently-editorial-protective-philosophy.trycloudflare.com/auth/callback",
  "https://currently-editorial-protective-philosophy.trycloudflare.com/auth/shopify/callback",
  "https://currently-editorial-protective-philosophy.trycloudflare.com/api/auth/callback",
  "https://currently-editorial-protective-philosophy.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "holo-apps.myshopify.com"
